class TextConstants {
  // App Titles
  static const String appName = "ZiyaAttend";
  static const String appSubtitle = "Smart Attendance Maintainer";

  // Common Dashboard Labels
  static const goodMorning = "Good Morning,";
  static const overview = "Overview";
  static const dashboard = "Dashboard";
  static const presence = "Presence";
  static const absence = "Absence";
  static const leaves = "Leaves";
  static const attendance = "Attendance";
  static const leaveStatus = "Leave Status";
  static const holidayList = "Holiday List";
  static const payslip = "Payslip";
  static const reports = "Reports";
  static const onSite = "On Site";
  static const qrVerification = "QR Verification";
  static const captureQRCode = "Please capture your QR Code";
  static const takePhoto = "Take Photo";
  static const punchInSuccess = "Punch in successfully";
  static const punchOutSuccess = "Punch out successfully";

  // Attendance Screen
  static const String workMode = "Work Mode";
  static const String dateLabel = "June 18, 2025";
  static const String status = "Status";
  static const String verification = "Verification";
  static const String selfie = "Selfie";
  static const String location = "Location";
  static const String locationValue = "Lat:13.05,Long:80.24";
  static const String notes = "Notes";
  static const String checkIn = "Check-in";
  static const String checkInTime = "09:30 AM";
  static const String checkOut = "Check-out";
  static const String checkOutTime = "06:00 PM";
  static const String present = "Present";
  static const String office = "Office";
  static const String workedNote = "Worked On UI Bug Fixing";
  static const String june18 = "June 18, 2025";
  static const String monthYearFormat = "MMMM yyyy";
  static const String attendanceCalendar = "Attendance Calendar";
  static const String options = "Attendance Calendar";

  // Payslip
  static const String payslipTitle = "Payslip";
  static const String employeeSummary = "EMPLOYEE SUMMARY";
  static const String amountInWordsLabel = "Amount in Words:";
  static const String generatedNote = "-This document has been automatically generated by Ziya Academy";
  static const String downloadButtonText = "Download the sample salary slip format for PDF";
  static const String payslipMonthPrefix = "Payslip for the Month";
  static const String monthlyPayslipHistory = "Monthly Payslip History";
  static const String companyName = "ZiyaAcademy";
  static const String companyTagline = "KEY-TO SUCCESS";
  static const String oops = "Oops!";
  static const String noPreviousPage = "No previous page available";

  // Leave Screen
  static const String applyLeaveTitle = "Apply for Leave";
  static const String employeeName = "Employee Name";
  static const String employeeNameHint = "Employee Name - auto-filled";
  static const String employeeID = "Employee ID";
  static const String employeeIDHint = "Employee ID - auto-filled";
  static const String fromDate = "From Date";
  static const String toDate = "To Date";
  static const String leaveType = "Leave Type";
  static const String reasonLabel = "Reason";
  static const String reasonHint = "Type your reason...";
  static const String attachment = "Attachment";
  static const String fileoptions = "No file chosen";
  static const String chooseType = "Choose Type";
  static const String formSuccess = "Form submitted successfully!";
  static const String selectFromDateFirst = "Please select From Date first.";
  static const String sickLeave = "Sick Leave";
  static const String casualLeave = "Casual Leave";
  static const String emergencyLeave = "Emergency Leave";

  // Forgot Password
  static const String oopss = "Oops! Forgot Password?";
  static const String resetInstruction = "Enter your registered email address \nto reset your password.";
  static const String emailRequired = "Email is required";
  static const String invalidEmail = "Enter a valid email address";
  static const String resetPassword = "Reset Password";
  static const String backToLogin = "Back To Login";

  // Login Texts
  static const String email = "Email";
  static const String password = "Password";
  static const String login = "Login";
  static const String forgotPassword = "Forgot Password?";
  static const String dontHaveAccount = "Don't have an account?";
  static const String signUp = "Sign Up";

  // Validation Messages
  static const String enterEmail = "Enter Email";
  static const String enterValidEmail = "Enter a valid email";
  static const String enterPassword = "Enter Password";
  static const String passwordLength = "Password must be at least 6 characters";

  // Signup Page
  static const String createAccount = "Create an account";
  static const String name = "Name";
  static const String mobile = "Mobile Number";
  static const String confirmPassword = "Confirm Password";
  static const String alreadyHaveAccount = "Already have an account? Login";
  static const String signupSuccess = "Signup successful!";
  static const String enterName = "Enter Name";
  static const String enterMobile = "Enter Mobile Number";
  static const String enterValidMobile = "Enter 10-digit mobile number";
  static const String enterConfirmPassword = "Enter Confirm Password";
  static const String passwordMismatch = "Passwords do not match";

  // Leave Taken Summary
  static const String totalLeaveTaken = "Total Leave Taken";
  static const String approvalRate = "Approval Rate";
  static const String pendingRequest = "Pending Request";
  static const String teamMemberOnLeave = "Team Member on Leave";
  static const String leaveOverview = "Leave Overview";
  static const String leaveDistribution = "Your leave distribution for the current year";
  static const String leaveDaysTaken = "Leave days taken";
  static const String totalDays = "Total days";
  static const String remaining = "Remaining";
  static const String upcomingLeave = "Upcoming Leave";
  static const String scheduledTimeOff = "Your scheduled time off";
  static const String annualLeave = "Annual Leave";
  static const String leaveDateRange = "April 22, 2025 to Apr 24, 2025 (3 days)";
  static const String pending = "Pending";
  static const String leavePendingNote = "Your leave request is awaiting manager approval.";
  static const String leaveTaken = "Leave Taken";
  static const String leaveBalance = "Leave Balance";
  static const String approvedLeaves = "Approved Leaves";
  static const String rejectedLeaves = "Rejected Leaves";
  static const String upcomingLeaves = "Upcoming \n Leaves";
  static const String scheduledLeaveDate = "Scheduled (25 June)";
  static const String remainingThisMonth10 = "10 days remaining this month";
  static const String remainingThisMonth25 = "25 days remaining this month";
  static const String remainingThisMonth29 = "29 days remaining this month";

  // Face Verification
  static const String faceTitle = "Center your face";
  static const String faceSubtitle = "Point your face right at the box,\nthen take a photo";
  static const String faceVerificationTitle = "Face Verification";
  static const String faceVerificationInstruction = "Please capture your face";

  // Notifications
  static const String notificationsTitle = "Notifications";
  static const String missedPunch = "Missed Punch";
  static const String missedPunchMessage = "Missed Clock-in Detected. Please update your attendance or contact HR.";
  static const String lateAttendance = "Late Attendance";
  static const String lateAttendanceMessage = "You're running late! Your clock-in time is beyond the scheduled shift start.";
  static const String dailySummary = "Daily Summary";
  static const String dailySummaryMessage = "Your attendance today: Clock-in at 9:12 AM, Clock-out at 6:05 PM. Total hours: 8.53";
  static const String leaveApproval = "Leave Approval";
  static const String leaveApprovalMessage = "Your leave request for June 15 has been approved. Enjoy your day off!";
  static const String leaveRejection = "Leave Rejection";
  static const String leaveRejectionMessage = "Leave request declined. Please check with your manager for details.";
  static const String shiftUpdate = "Shift Update";
  static const String shiftUpdateMessage = "Shift updated: New shift time is 10:00 AM – 7:00 PM, effective from June 14.";

  // Report Legends
  static const String avgHours = "Avg hrs";

  // Search Bar
  static const String searchPlaceholder = "Search";
  static const String searchHistory = "Search History";

}
